import { useState } from "react";
import { Edit3, Layers3, Plus, Save, UserPlus } from "lucide-react";

import { AdminShell, Button, PageHead, Pill, SectionTitle, SyncNote } from "./_shared/AppShell";
import "./_group.css";

export function AcademicSetup() {
  const [level, setLevel] = useState("O-Level");
  const [showForm, setShowForm] = useState(false);
  const [saved, setSaved] = useState(false);
  const rows = level === "A-Level" ? [["S6 North", "PCM + Sub-ICT", "A. Derick", "22"], ["S6 South", "HEG + GP", "S. Nyakato", "19"], ["S5 East", "HGE + Sub-Maths", "M. Atwine", "31"]] : level === "Primary" ? [["P7", "General", "R. Kyomuhendo", "52"], ["P6", "General", "E. Twebaze", "48"], ["P5", "General", "J. Kabagambe", "46"]] : [["S4 East", "O-Level", "P. Mugisha", "45"], ["S4 West", "O-Level", "J. Kabarole", "44"], ["S3 East", "O-Level", "S. Nyakato", "41"], ["S3 West", "O-Level", "D. Tumusiime", "40"]];
  return <AdminShell page="setup" eyebrow="Academic setup" title="Academic structure">
    <PageHead eyebrow="School records · 2026" title="Shape the school around how it runs." description="Manage levels, class lists, streams, subjects and the teachers responsible for each markbook." actions={<><Button kind="quiet" icon={<UserPlus size={14} />} onClick={() => setShowForm(true)}>Assign teacher</Button><Button kind="gold" icon={<Plus size={14} />} onClick={() => setShowForm(true)}>Add class / stream</Button></>} />
    <div className="srm-tabs">{["Primary", "O-Level", "A-Level"].map((item) => <button key={item} className={`srm-tab ${level === item ? "active" : ""}`} onClick={() => setLevel(item)}>{item}<span style={{ color: "var(--srm-muted)", marginLeft: 6, fontSize: 9 }}>{item === "Primary" ? "7 classes" : item === "O-Level" ? "16 streams" : "5 combinations"}</span></button>)}</div>
    {showForm && <div className="srm-card srm-card-pad" style={{ marginBottom: 18, borderColor: "var(--srm-gold)" }}><div className="srm-section-title"><div><h2>New class or stream</h2><p>Add it to the {level} register.</p></div><button className="srm-icon-btn" onClick={() => setShowForm(false)}>×</button></div><div className="srm-grid srm-grid-3"><div className="srm-field"><label>Class name</label><input className="srm-input" defaultValue={level === "Primary" ? "P4" : "S4"} /></div><div className="srm-field"><label>Stream or combination</label><input className="srm-input" placeholder={level === "A-Level" ? "e.g. BCM + GP" : "e.g. East"} /></div><div className="srm-field"><label>Class teacher</label><select className="srm-input"><option>Choose teacher</option><option>P. Mugisha</option><option>J. Kabarole</option><option>S. Nyakato</option></select></div></div><Button kind="primary" icon={<Save size={14} />} onClick={() => { setSaved(true); setShowForm(false); }}>Save class</Button>{saved && <span style={{ marginLeft: 12, color: "var(--srm-teal)", fontSize: 10 }}>Saved to this device.</span>}</div>}
    <div className="srm-grid srm-grid-2" style={{ marginBottom: 18 }}>
      <section className="srm-card srm-card-pad"><SectionTitle title="Levels in this school" detail="Each level can use its own grading scheme." /><div style={{ display: "grid", gap: 10 }}>{[["Primary", "PLE-style", "7 classes", "84%", "gold"], ["O-Level", "UCE · CA 20% + Exam 80%", "16 streams", "91%", "teal"], ["A-Level", "UACE · principal + subsidiary", "5 combinations", "76%", "rust"]].map(([name, scheme, count, progress, tone]) => <button key={name} onClick={() => setLevel(name)} style={{ border: level === name ? "1px solid var(--srm-gold)" : "1px solid var(--srm-line)", background: level === name ? "#f8f0dc" : "transparent", borderRadius: 10, padding: 13, textAlign: "left", display: "flex", justifyContent: "space-between", alignItems: "center" }}><div><b style={{ fontSize: 12 }}>{name}</b><div style={{ fontSize: 9, color: "var(--srm-muted)", marginTop: 4 }}>{scheme} · {count}</div></div><Pill tone={tone as "teal" | "gold" | "rust"}>{progress} filled</Pill></button>)}</div></section>
      <section className="srm-card srm-card-pad"><SectionTitle title="Subjects offered" detail={`${level} subject register`} action={<button className="srm-link" onClick={() => setSaved(true)}><Plus size={12} style={{ verticalAlign: "middle" }} /> Add subject</button>} /><div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>{(level === "A-Level" ? ["Mathematics", "Physics", "Chemistry", "Biology", "Economics", "History", "Geography", "General Paper", "Sub-ICT"] : ["Mathematics", "English Language", "Physics", "Chemistry", "Biology", "History", "Geography", "Luganda", "ICT", "Agriculture"]).map((subject, i) => <span key={subject} className="srm-pill srm-pill-ink">{subject}<button onClick={() => setSaved(true)} style={{ border: 0, background: "transparent", padding: 0, color: "var(--srm-muted)" }}>×</button></span>)}</div><div style={{ marginTop: 24 }}><SyncNote /></div></section>
    </div>
    <section className="srm-card srm-card-pad"><SectionTitle title={`${level} classes and streams`} detail="Every learner belongs to one class + stream + level." action={<button className="srm-link" onClick={() => setShowForm(true)}>Edit register <Edit3 size={12} style={{ verticalAlign: "middle" }} /></button>} /><div className="srm-table-wrap"><table className="srm-table"><thead><tr><th>Class / stream</th><th>{level === "A-Level" ? "Combination" : "Scheme"}</th><th>Class teacher</th><th>Students</th><th>Markbook</th><th /></tr></thead><tbody>{rows.map(([name, combination, teacher, students]) => <tr key={name}><td><b>{name}</b><div style={{ color: "var(--srm-muted)", fontSize: 9, marginTop: 3 }}>{level} · Term 3</div></td><td>{combination}</td><td>{teacher}</td><td className="srm-mono">{students}</td><td><Pill tone={name.includes("S3 West") ? "rust" : "teal"}>{name.includes("S3 West") ? "Needs marks" : "Assigned"}</Pill></td><td><button className="srm-icon-btn" onClick={() => setSaved(true)}><Layers3 size={14} /></button></td></tr>)}</tbody></table></div></section>
  </AdminShell>;
}
