import { useState } from "react";
import { ArrowDownRight, ArrowUpRight, Filter, Search, TrendingUp } from "lucide-react";

import { AdminShell, Button, PageHead, Pill, SectionTitle, TinyChart } from "./_shared/AppShell";
import "./_group.css";

export function MarksPerformance() {
  const [subject, setSubject] = useState("All subjects");
  const [period, setPeriod] = useState("Term 3 · 2026");
  return <AdminShell page="performance" eyebrow="Marks & performance" title="Marks tell a useful story">
    <PageHead eyebrow="Assessment intelligence" title="Find the signal before reports." description="Track completion, compare class progress, and see where a teacher or learner needs support." actions={<><Button kind="quiet" icon={<Filter size={14} />} onClick={() => setSubject("Mathematics")}>Filter view</Button><Button kind="gold" icon={<TrendingUp size={14} />} onClick={() => setPeriod("Export ready")}>Export analysis</Button></>} />
    <div className="srm-grid srm-grid-4" style={{ marginBottom: 19 }}>
      <div className="srm-card srm-card-pad srm-stat"><div className="srm-stat-top"><span>School mean</span><TrendingUp size={16} color="var(--srm-teal)" /></div><strong>72.6%</strong><div className="srm-stat-foot"><b>+4.2 pts</b> compared with Term 2</div></div>
      <div className="srm-card srm-card-pad srm-stat"><div className="srm-stat-top"><span>Above 70%</span><ArrowUpRight size={16} color="var(--srm-teal)" /></div><strong>694</strong><div className="srm-stat-foot">of 1,240 learners</div></div>
      <div className="srm-card srm-card-pad srm-stat"><div className="srm-stat-top"><span>Needs support</span><ArrowDownRight size={16} color="var(--srm-rust)" /></div><strong>118</strong><div className="srm-stat-foot">below 50% in 2+ subjects</div></div>
      <div className="srm-card srm-card-pad srm-stat"><div className="srm-stat-top"><span>Data quality</span><Search size={16} color="var(--srm-gold)" /></div><strong>94.8%</strong><div className="srm-stat-foot"><b>Strong</b> · 43 missing CA entries</div></div>
    </div>
    <div className="srm-grid srm-grid-2" style={{ marginBottom: 18 }}>
      <section className="srm-card srm-card-pad"><SectionTitle title="Mean score over time" detail="Published results, all levels" action={<select className="srm-input" value={period} onChange={(e) => setPeriod(e.target.value)} style={{ width: 130, padding: "7px 8px", fontSize: 10 }}><option>Term 3 · 2026</option><option>Term 2 · 2026</option><option>All terms</option></select>} /><TinyChart values={[61, 64, 63, 67, 69, 72, 73]} labels={["T1 '24", "T2 '24", "T3 '24", "T1 '25", "T2 '25", "T3 '25", "T3 '26"]} /><div className="srm-note" style={{ marginTop: 4 }}>The school mean has risen steadily over the last four published terms. The largest gain is in O-Level Science.</div></section>
      <section className="srm-card srm-card-pad"><SectionTitle title="Subject pulse" detail="Average final mark · current term" action={<select className="srm-input" value={subject} onChange={(e) => setSubject(e.target.value)} style={{ width: 130, padding: "7px 8px", fontSize: 10 }}><option>All subjects</option><option>Mathematics</option><option>Science</option></select>} /><div style={{ display: "grid", gap: 15, paddingTop: 6 }}>{[["English Language", 78, "+5.2", "teal"], ["Mathematics", 74, "+2.4", "teal"], ["Biology", 68, "+6.1", "gold"], ["Physics", 61, "-1.8", "rust"], ["History", 59, "+0.9", "gold"]].map(([name, value, delta, tone]) => <div key={name}><div style={{ display: "flex", justifyContent: "space-between", fontSize: 10, marginBottom: 6 }}><span>{name}</span><span><b>{value}%</b> <span style={{ color: tone === "rust" ? "var(--srm-rust)" : "var(--srm-teal)", marginLeft: 7 }}>{delta}</span></span></div><div className="srm-progress"><span style={{ width: `${value}%`, background: tone === "rust" ? "var(--srm-rust)" : tone === "gold" ? "var(--srm-gold)" : "var(--srm-teal)" }} /></div></div>)}</div></section>
    </div>
    <section className="srm-card srm-card-pad"><SectionTitle title="Classes requiring attention" detail="Prioritised by missing marks and learner movement" action={<button className="srm-link" onClick={() => setSubject("Needs attention")}>See intervention notes <ArrowUpRight size={12} style={{ verticalAlign: "middle" }} /></button>} /><div className="srm-table-wrap"><table className="srm-table"><thead><tr><th>Class</th><th>Mean</th><th>Change</th><th>Missing entries</th><th>Teacher</th><th>Suggested next step</th></tr></thead><tbody>{[["S3 West", "56.8%", "-4.1 pts", "18", "J. Kabarole", "Complete CA before reports"], ["S6 South · HEG", "64.2%", "+1.6 pts", "6", "S. Nyakato", "Review Geography cohort"], ["S4 East", "78.9%", "+6.2 pts", "0", "P. Mugisha", "Share Mathematics practice"]].map(([name, mean, change, missing, teacher, next]) => <tr key={name}><td><b>{name}</b></td><td className="srm-mono">{mean}</td><td><span style={{ color: change.startsWith("-") ? "var(--srm-rust)" : "var(--srm-teal)", fontWeight: 700 }}>{change}</span></td><td><Pill tone={missing === "0" ? "teal" : "rust"}>{missing === "0" ? "Complete" : `${missing} to review`}</Pill></td><td>{teacher}</td><td style={{ color: "var(--srm-muted)", fontSize: 10 }}>{next}</td></tr>)}</tbody></table></div></section>
  </AdminShell>;
}
