import { useState } from "react";
import { Check, Download, FileText, MoreHorizontal, Printer, Send, Sparkles } from "lucide-react";

import { AdminShell, Button, PageHead, Pill, SectionTitle } from "./_shared/AppShell";
import "./_group.css";

const subjectRows = [["Mathematics", "80", "88", "77", "85", "86", "A", "Exceptional"], ["English Language", "77", "84", "81", "82", "83", "A", "Exceptional"], ["Physics", "68", "72", "70", "74", "71", "B", "Outstanding"], ["Chemistry", "74", "68", "76", "72", "70", "B", "Outstanding"]];

export function ReportsTemplates() {
  const [template, setTemplate] = useState("Classic");
  const [sent, setSent] = useState(false);
  const [tab, setTab] = useState("Preview");
  return <AdminShell page="reports" eyebrow="Reports & templates" title="Reports that feel worth sending home">
    <PageHead eyebrow="Term 3 · 2026" title="Prepare the final page." description="Choose a clean school template, review a real report card, then print or send a whole class." actions={<><Button kind="quiet" icon={<Download size={14} />} onClick={() => setSent(true)}>Export class ZIP</Button><Button kind="gold" icon={<Printer size={14} />} onClick={() => window.print()}>Print preview</Button></>} />
    <div className="srm-tabs">{["Preview", "Template library", "Comments & signatures"].map(item => <button className={`srm-tab ${tab === item ? "active" : ""}`} key={item} onClick={() => setTab(item)}>{item}</button>)}</div>
    {tab === "Template library" ? <div className="srm-grid srm-grid-3">{[["Classic", "Warm gold rules · generous writing room"], ["Modern Green", "Bold name bar · quick scanning"], ["Plain B/W", "Economical · copier friendly"]].map(([name, description], i) => <button key={name} onClick={() => { setTemplate(name); setTab("Preview"); }} className="srm-card srm-card-pad" style={{ textAlign: "left", border: template === name ? "2px solid var(--srm-gold)" : "1px solid var(--srm-line)" }}><div style={{ height: 150, background: i === 0 ? "#f9f1dd" : i === 1 ? "#e1efea" : "#f3f3ef", border: "1px solid #cbd3ca", padding: 14, marginBottom: 14 }}><div style={{ textAlign: "center", borderBottom: `2px solid ${i === 1 ? "var(--srm-teal)" : "var(--srm-ink)"}`, paddingBottom: 7, fontSize: 9 }}><b>TOORO SECONDARY SCHOOL</b><br />TERM 3 REPORT</div><div style={{ height: 40, marginTop: 10, background: i === 1 ? "var(--srm-teal)" : "#e5dfd0", opacity: .8 }} /><div style={{ height: 5, width: "75%", background: "#cdd8cd", marginTop: 9 }} /></div><b style={{ fontSize: 13 }}>{name}</b><p style={{ color: "var(--srm-muted)", fontSize: 10, margin: "5px 0 13px" }}>{description}</p>{template === name && <Pill tone="gold"><Check size={11} /> In use</Pill>}</button>)}</div> : <div className="srm-grid" style={{ gridTemplateColumns: "minmax(0, 1.4fr) minmax(280px, .6fr)", alignItems: "start" }}><section className="srm-card srm-card-pad"><SectionTitle title="Live report preview" detail="Mary Aine · S4 East · Position 1 of 45" action={<Pill tone="teal">Ready to print</Pill>} /><div className="srm-report-paper">
      <div className="srm-report-head"><div className="srm-crest">TS</div><h2>TOORO SECONDARY SCHOOL</h2><p>Kyenjojo District, Uganda · P.O. Box 48 · 0772 418 906</p><p>“Knowledge is Light”</p><strong>END OF TERM 3 REPORT · 2026</strong></div>
      <div className="srm-report-student"><img src="/__mockup/images/mary-aine.jpg" alt="Mary Aine student portrait" /><div><strong>Mary Aine</strong><p>Admission no. TSS-2024-001 · Date of birth: 14 May 2010</p><p><b>Class:</b> S4 &nbsp; <b>Stream:</b> East &nbsp; <b>Level:</b> O-Level</p></div><div className="srm-report-metric"><b>1 / 45</b><span>CLASS POSITION</span></div></div>
      <div className="srm-table-wrap"><table className="srm-table srm-report-table"><thead><tr><th style={{ textAlign: "left" }}>Subject</th><th>CA 20%</th><th>Exam 80%</th><th>AoI</th><th>Project</th><th>Total</th><th>Grade</th><th>Remark</th></tr></thead><tbody>{subjectRows.map(row => <tr key={row[0]}><td style={{ textAlign: "left" }}><b>{row[0]}</b></td>{row.slice(1).map((cell, i) => <td key={`${row[0]}-${i}`} style={{ fontWeight: i === 4 || i === 5 ? 700 : 400 }}>{cell}</td>)}</tr>)}</tbody><tfoot><tr><td style={{ textAlign: "left" }}><b>OVERALL</b></td><td colSpan={3}>312 / 400</td><td><b>77.8%</b></td><td><b>A</b></td><td colSpan={2}><b>Qualified</b></td></tr></tfoot></table></div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 150px", gap: 15, marginTop: 16, alignItems: "center" }}><div><svg viewBox="0 0 240 55" width="100%" height="55" role="img" aria-label="Mary Aine performance graph"><polyline points="8,38 62,26 116,32 170,16 226,10" fill="none" stroke="var(--srm-teal)" strokeWidth="2.5" /><polyline points="8,38 62,26 116,32 170,16 226,10" fill="none" stroke="var(--srm-teal)" strokeWidth="7" opacity=".09" /><text x="8" y="52" fontSize="7" fill="#65756b">T1 '25</text><text x="108" y="52" fontSize="7" fill="#65756b">T2 '25</text><text x="209" y="52" fontSize="7" fill="#65756b">T3 '26</text></svg><div style={{ color: "var(--srm-muted)", fontSize: 8 }}>Performance trend · 68% → 78%</div></div><div style={{ borderLeft: "1px solid #dfe5df", paddingLeft: 13, fontSize: 9 }}><b>Attendance</b><br /><span style={{ color: "var(--srm-muted)" }}>Present 58 / 62 days</span><br /><span style={{ color: "var(--srm-teal)" }}>93.5% present</span></div></div>
      <div className="srm-report-footer-grid"><div className="srm-comment"><b>Class teacher's comment</b>Mary is disciplined and creative. Excellent application of knowledge. Keep asking brave questions next term.<br /><span style={{ color: "var(--srm-teal)", fontSize: 8 }}>P. Mugisha · signed 18 Nov 2026</span></div><div className="srm-comment"><b>Head teacher's comment</b>Outstanding performance. We are proud of this steady progress.<br /><span style={{ color: "var(--srm-teal)", fontSize: 8 }}>A. Derick · approved</span></div></div>
      <div className="srm-signatures"><div>Class Teacher</div><div>Head Teacher</div><div>Parent / Guardian</div></div>
    </div></section>
    <aside style={{ display: "grid", gap: 15 }}><section className="srm-card srm-card-pad"><SectionTitle title="Template in use" detail="Applied to O-Level report cards" /><div style={{ display: "flex", alignItems: "center", gap: 12, border: "1px solid var(--srm-gold)", background: "#f8f0dc", padding: 12, borderRadius: 9 }}><Sparkles size={17} color="var(--srm-gold)" /><div><b style={{ fontSize: 12 }}>{template}</b><div style={{ color: "var(--srm-muted)", fontSize: 9, marginTop: 3 }}>School details and signatures included</div></div></div><button className="srm-link" style={{ marginTop: 12 }} onClick={() => setTab("Template library")}>Browse all templates <MoreHorizontal size={12} style={{ verticalAlign: "middle" }} /></button></section><section className="srm-card srm-card-pad"><SectionTitle title="Report actions" detail="This preview is for Mary Aine." /><div style={{ display: "grid", gap: 8 }}><Button kind="gold" icon={<Printer size={14} />} onClick={() => window.print()}>Print this report</Button><Button kind="primary" icon={<Send size={14} />} onClick={() => setSent(true)}>Send class bundle</Button><Button kind="quiet" icon={<Download size={14} />} onClick={() => setSent(true)}>Save PDF copy</Button></div>{sent && <div style={{ color: "var(--srm-teal)", fontSize: 10, marginTop: 12, display: "flex", gap: 5, alignItems: "center" }}><Check size={13} /> Added to the offline send queue.</div>}</section><div className="srm-note">Every printed report keeps the grading scheme used for that term. A USB bundle is ready even without internet.</div></aside></div>}
  </AdminShell>;
}
