import { useState } from "react";
import { Check, ChevronDown, ChevronUp, CircleAlert, Save, Search, Undo2 } from "lucide-react";

import { Button, Pill, TeacherShell } from "./_shared/AppShell";
import "./_group.css";

const students = [["Mary Aine", "88", "A", "83%", "strong"], ["Peter Kato", "58", "C", "61%", "steady"], ["Grace Ninsiima", "79", "B", "76%", "strong"], ["Eric Mugisha", "", "—", "48%", "missing"], ["Sarah Atuha", "91", "A", "89%", "strong"], ["Joel Byamugisha", "64", "C", "66%", "steady"]];

export function TeacherMarks() {
  const [assessment, setAssessment] = useState("EOT");
  const [scores, setScores] = useState<Record<string, string>>({ "Eric Mugisha": "" });
  const [saved, setSaved] = useState(false);
  const [selected, setSelected] = useState("Mary Aine");
  const saveMarks = () => setSaved(true);
  return <TeacherShell page="marks">
    <div className="srm-teacher-card" style={{ paddingBottom: 11 }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "start", gap: 12 }}><div><div style={{ color: "var(--srm-muted)", fontSize: 10, marginBottom: 5 }}>MARKBOOK</div><h2 style={{ font: "400 19px Georgia, serif", margin: 0 }}>Mathematics</h2><p style={{ color: "var(--srm-muted)", fontSize: 10, margin: "5px 0 0" }}>S4 East · 45 learners · Term 3</p></div><Pill tone={saved ? "teal" : "gold"}>{saved ? "Saved locally" : "12 to enter"}</Pill></div><div className="srm-tabs" style={{ marginTop: 18, marginBottom: 0 }}>{["Exams", "CA · 20%", "AoI", "Project"].map(item => <button className={`srm-tab ${item === "Exams" ? "active" : ""}`} key={item} onClick={() => setAssessment(item)}>{item}</button>)}</div></div>
    <div className="srm-teacher-card"><div style={{ display: "flex", gap: 7, marginBottom: 12 }}>{["BOT", "MID", "EOT"].map(item => <button key={item} onClick={() => setAssessment(item)} className={assessment === item ? "srm-btn srm-btn-primary" : "srm-btn srm-btn-quiet"} style={{ padding: "7px 11px", fontSize: 10 }}>{item}</button>)}</div><div className="srm-note" style={{ marginBottom: 12, display: "flex", gap: 7, alignItems: "start" }}><CircleAlert size={14} color="var(--srm-gold)" /><span><b>UCE final mark is calculated automatically.</b> 20% continuous assessment + 80% EOT. Enter a whole number from 0 to 100.</span></div>{students.map(([name, original, grade, average, state], i) => <div className="srm-student-row" key={name} style={{ cursor: "pointer", background: selected === name ? "#f8f3e7" : "transparent", margin: "0 -8px", padding: "12px 8px", borderRadius: 8 }} onClick={() => setSelected(name)}><div className="srm-student-name"><span className="srm-student-number">{String(i + 1).padStart(2, "0")}</span><div><b>{name}</b><div style={{ color: "var(--srm-muted)", fontSize: 9, marginTop: 3 }}>Current average {average} · <span style={{ color: state === "missing" ? "var(--srm-rust)" : "var(--srm-teal)" }}>{state}</span></div></div></div><div style={{ display: "flex", alignItems: "center", gap: 8 }}><span style={{ fontSize: 9, color: "var(--srm-muted)" }}>Grade {grade}</span><input className={`srm-score ${!scores[name] && state === "missing" ? "missing" : ""}`} aria-label={`${name} score`} value={scores[name] ?? original} placeholder="—" onChange={(e) => { setScores({ ...scores, [name]: e.target.value }); setSaved(false); }} onClick={(e) => e.stopPropagation()} /></div></div>)}</div>
    <div className="srm-teacher-card" style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap" }}><div style={{ display: "flex", gap: 10, alignItems: "center", color: "var(--srm-muted)", fontSize: 10 }}><Save size={15} color="var(--srm-teal)" /><span>{saved ? "Saved to this phone at 09:43" : "Not saved yet · changes are local until saved"}</span></div><div style={{ display: "flex", gap: 7 }}><Button kind="quiet" icon={<Undo2 size={13} />} onClick={() => { setScores({ "Eric Mugisha": "" }); setSaved(false); }}>Undo changes</Button><Button kind="gold" icon={<Check size={13} />} onClick={saveMarks}>Save marks</Button></div></div>
    <div className="srm-teacher-card"><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><div><h2 style={{ marginBottom: 4 }}>Performance context</h2><p style={{ margin: 0, color: "var(--srm-muted)", fontSize: 10 }}>Selected learner · {selected}</p></div><button className="srm-icon-btn" onClick={() => setSelected(selected === "Mary Aine" ? "Peter Kato" : "Mary Aine")}><Search size={14} /></button></div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, marginTop: 14 }}><div style={{ padding: 12, background: "var(--srm-teal-soft)", borderRadius: 9 }}><div style={{ color: "var(--srm-muted)", fontSize: 9 }}>Term average</div><b style={{ display: "block", font: "400 25px Georgia, serif", marginTop: 5 }}>83%</b><span style={{ color: "var(--srm-teal)", fontSize: 9 }}>+6 pts from Term 2</span></div><div style={{ padding: 12, background: "#f2eee4", borderRadius: 9 }}><div style={{ color: "var(--srm-muted)", fontSize: 9 }}>Class position</div><b style={{ display: "block", font: "400 25px Georgia, serif", marginTop: 5 }}>1 / 45</b><span style={{ color: "var(--srm-muted)", fontSize: 9 }}>Keep the momentum</span></div></div></div>
    <div style={{ color: "var(--srm-muted)", fontSize: 9, display: "flex", alignItems: "center", gap: 5, justifyContent: "center" }}><ChevronDown size={13} /> Keyboard tip: Enter saves the score, Down moves to the next learner <ChevronUp size={13} /></div>
  </TeacherShell>;
}
