import { useState } from "react";
import { ArrowRight, Check, Clock3, FileText, PenLine, Send, Users } from "lucide-react";

import { Button, Pill, TeacherShell } from "./_shared/AppShell";
import "./_group.css";

export function TeacherHome() {
  const [queue, setQueue] = useState(0);
  return <TeacherShell page="home">
    <div className="srm-teacher-card" style={{ marginTop: -2, display: "flex", alignItems: "center", gap: 13 }}><div className="srm-crest">TS</div><div style={{ flex: 1 }}><b style={{ fontSize: 12 }}>Tooro Secondary School</b><p style={{ margin: "3px 0 0", color: "var(--srm-muted)", fontSize: 10 }}>S4 · East · 45 students · UCE scheme</p></div><Pill tone="teal">Term 3</Pill></div>
    <div className="srm-grid srm-grid-2" style={{ gap: 10, marginBottom: 14 }}><div className="srm-teacher-card" style={{ margin: 0, background: "var(--srm-ink)", color: "#fff" }}><div style={{ color: "#a9c3b6", fontSize: 10 }}>CA entries pending</div><strong style={{ font: "400 29px Georgia, serif", display: "block", marginTop: 8 }}>12</strong><div style={{ color: "#a9c3b6", fontSize: 9, marginTop: 4 }}>across 3 subjects</div></div><div className="srm-teacher-card" style={{ margin: 0 }}><div style={{ color: "var(--srm-muted)", fontSize: 10 }}>Exams complete</div><strong style={{ font: "400 29px Georgia, serif", display: "block", marginTop: 8 }}>45/45</strong><div style={{ color: "var(--srm-teal)", fontSize: 9, marginTop: 4 }}>Ready for comments</div></div></div>
    <div className="srm-teacher-card"><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 13 }}><h2 style={{ margin: 0 }}>Your markbooks</h2><Pill tone="gold">3 active</Pill></div>{[["Mathematics", "EOT exam · 45 learners", "Complete", "teal"], ["English Language", "CA · 20% · 12 missing", "Needs attention", "rust"], ["Physics", "Activity of Integration · 22 learners", "In progress", "gold"]].map(([name, meta, status, tone]) => <div className="srm-task" key={name}><div style={{ display: "flex", gap: 10, alignItems: "center" }}><div style={{ width: 30, height: 30, borderRadius: 8, background: "var(--srm-teal-soft)", color: "var(--srm-teal)", display: "grid", placeItems: "center" }}>{name === "Mathematics" ? <FileText size={15} /> : name === "Physics" ? <Clock3 size={15} /> : <PenLine size={15} />}</div><div><div className="srm-task-title">{name}</div><div className="srm-task-meta">{meta}</div></div></div><div style={{ display: "flex", alignItems: "center", gap: 7 }}><Pill tone={tone as "teal" | "gold" | "rust"}>{status}</Pill><ArrowRight size={14} color="var(--srm-muted)" /></div></div>)}</div>
    <div className="srm-teacher-card"><h2>Today at a glance</h2><div className="srm-grid srm-grid-2" style={{ gap: 10 }}><div style={{ padding: 12, background: "#f2eee4", borderRadius: 9 }}><Users size={16} color="var(--srm-gold)" /><b style={{ display: "block", fontSize: 11, marginTop: 9 }}>2 students</b><span style={{ color: "var(--srm-muted)", fontSize: 9 }}>need a performance note</span></div><div style={{ padding: 12, background: "var(--srm-teal-soft)", borderRadius: 9 }}><Send size={16} color="var(--srm-teal)" /><b style={{ display: "block", fontSize: 11, marginTop: 9 }}>{queue} queued</b><span style={{ color: "var(--srm-muted)", fontSize: 9 }}>reports waiting to send</span></div></div></div>
    <div className="srm-note" style={{ marginBottom: 14 }}><b>Auto-send is off.</b> Your markbook remains entirely on this phone until you choose Wi-Fi send or export a USB bundle.</div>
    <Button kind="gold" onClick={() => setQueue(1)} icon={<Check size={14} />}>Review and queue reports</Button>
  </TeacherShell>;
}
